### ISSUE TITLE
Instable connection

### ISSUE THREAD

**Issue by aranega** [aebruno/whisperfish#122]
Hi there,

I got a strange issue (not the first time), the "connected" status was flickering from "connected" to "disconnected" and it was impossible to send any messages. The only solution was to remove the whole database files (I made a backup) and make a new registration. The inconvenient with this solution is that I lost all the conversations... After the new registration, I tried to put back the "old" database, obviously, the discussions are back as they should, but the connection issue appeared again.

The issue seems to directly come from the db, I can live with the deletion of the db when the issue occurs, but is there a possibility to migrate conversation from the old db to the new one?

Thanks a lot for that awesome app!

**Comment by aebruno** [comment]
Sorry you're having troubles, I have not seen this error before. Next time it happens if you could capture some logs that would be great. If you start whisperfish with the `-d` option it will write debugging output to a file `/tmp/whisperfish-app.log`:
```
   $ harbour-whisperfish -d
```

Note: there may be sensitive info (contact numbers etc.) so you will want to sanitize the output before posting anywhere public.

**Comment by aebruno** [comment]
@laubblaeser Sorry to here you're having trouble. Think your best bet would be to start with a fresh install of Whisperfish, remove the data files and re-register. See [this issue](https://github.com/aebruno/whisperfish/issues/77#issuecomment-288986752) for starting over.
