### ISSUE TITLE
Send button looks out of place

### ISSUE THREAD

**Issue by ghost** [aebruno/whisperfish#24]
- [ ] The send button would look better as it is in the Messages application, with just text saying "Send", have "Signal" where it would normally say SMS/XMPP/Facebook/..., and a blue line as some kind of 'online indicator' (even though you can't be online/offline with Signal). Of course, it shouldn't say "Change type" when no text has been entered yet. Maybe just "Send", but greyed out.

**Comment by carepack** [comment]
you mean an integration into the stock messaging app?

**Comment by d9h02f** [comment]
Integration would be perfect, of course, but I'm only asking for the next best thing. Whisperfish is based on the layout of Messages anyway, might as well make it look even more like it. In any case the send button really doesn't fit with the general look of Sailfish.

I'd also say the double ticks could be replaced by some text saying "Sent" and afterwards "Delivered", which would look even more like Messages.

**Comment by carepack** [comment]
I agree to the send button itself, but I really like the ticks. In the jolla messaging app you also don't have sent or delivered indicators for facebook or google messages. I think also this would require more space which is unecessary. And also it would look more like signal on android.  In the end @aebruno have to decide.

**Comment by d9h02f** [comment]
I don't think it would need more space, the ticks are on a separate line with the timestamp, there's enough space to put a whole sentence. Of course this is more a matter of taste.

**Comment by carepack** [comment]
For this one I think you can open a new feature enhancement, so that it's more easy for bruno to have an overview instead of having multiple things together in one issue. I like the idea to have an option to switch between on- and offline in the app itself. When you're talking about a status indicator, do yo mean an integration to the jolla indicator like for system accounts like hangouts / facbook messenger plugin? I would only recommend it when a full system integration is possible. Else we would have something in split, and if I can't switch the on- and offline there it's more confusing. And to have to places to switch, in app and jolla settings, is one too much.

**Comment by carepack** [comment]
Yes, a matter of taste. But a discussion is always good to reach the best usability and design.

**Comment by aebruno** [comment]
I agree the send button does not fit the general look of Sailfish. The reasoning behind adding the button was to make Whisperfish look and feel similar to jolla-messages but have slightly different UI elements to indicate you're in a different app. If the send button looked the same as jolla-messages it would be hard to tell which app you're currently in. Having the button there clearly shows you're sending a secure message. Having said that, I could go either way. Let me think about it some more and see if I can come up with a better button. 

Thanks for all the great feedback. Much appreciated.

**Comment by d9h02f** [comment]
What you say is true, but as long as it says 'Signal' on the button as it says XMPP/SMS/... on the button in Messages, I think it should be okay. Otherwise the same argument could also be made to split Messages up into separate applications for SMS/XMPP/... because people could accidentally send an SMS when they wanted to send an XMPP message. Happens to me anyway, but I don't blame the application for it, it does what I tell it to do, I just told it to do the wrong thing.

**Comment by d9h02f** [comment]
As of 2.0.2, Messages now shows timestamps in text ("3 June" instead of "03/07/16"), it looks great and would definitely be a good fit on Whisperfish as well.
