### ISSUE TITLE
 Spamms messages into Group

### ISSUE THREAD

**Issue by Cthulien** [aebruno/whisperfish#54]
Hi all, 

Yesterday I wrote a message into a group conversation ant the following happened: 
1. Wrote 3 messages in the bus ( possibly bad internet connection) received 2 answers.  
2. Could not send or recive any further messages for the rest of the day. The app however showed that the messages where delivered to the server (with one check?)
3. Met the group of people in the conversation and they said I was spamming messages the whole day (~1000) and they send me messages which I didn't receive.
4. Stopped the app -> still spamming
5. Deinstalled the app -> still spamming 
6. restarted phone -> stopped 
7. Any ideas how to track this down? Would you consider this a problem of the app or as suggested of a dear friend of mine that is a problem of the websocket? 

Version information: 
Whisperfish: v0.3.0
Sailfish OS 2.0.2.43
Jolla C

**Comment by Cthulien** [comment]
It happend a second time. 
I digged a little into it and I noticed that it is within the app. For each spam message the app creates a new session in /storage/sessions for each member of the group. 
Apart from that a reboot does not stop the spamming.

**Comment by aebruno** [comment]
Sorry you're having trouble with the app. I'm not able to reproduce this but sounds like a nasty bug. Support for group messaging is still quite lacking and not very well tested. The fact that you uninstalled the app and it was still spamming is quite odd. If you stop the app it should not send any messages as there's no daemon process running. 

Are there any unsent messages (See: Settings -> Statistics -> Unsent messages)? Do you have any linked devices? Were the spam messages sent ones you wrote?

**Comment by Cthulien** [comment]
Sorry for the late reply I was on holliday.
Yes the spam messages where a repetition of messages I wrote. To be accurate it always happened, when I wrote more then one message in a short period of time with possibly bad internet connection. The group has 20 users and it is possible that in the second occasion the Internet connection was bad as well. I wouldn't be 100% sure that stopping the app didn't solve it if there would be a delay. It might have hit the time where I rebooted after stopping and uninstalling the app. 
Yes there are 2 unsent messages stored in the libray. No I had no other devices linked to that account.
For the moment I switched to libre signal.

**Comment by aebruno** [comment]
Thanks for the additional info. Working on trying to reproduce this and will hopefully have a fix for the next release.

**Comment by Cthulien** [comment]
Hi all,

I think I have an idea where the issue might come from.

Since I switched to whisper fish just before this issue came up it might be, that not all the users accepted my new identity. Accordingly not everybody could receive the message, which might have led to the false status of “not send” for all users, even though all the people who updated my identity received the message. My assumption is, that the message was stuck in an a loop until all users accepted my identity. Since this didn't happen the messenger kept spamming. 

When looking at the sessions some of the users did not get spammed in the second flood. Their session did not get updated and the time fits to the first spamming sessions aka my first group message. When I looked up their numbers they do not participate in the group regularly nor did I exchange keys with them in separate messages.  

I hope this helps.

**Comment by bonanza123** [comment]
I'm not fully sure whether what I observed today is really related to this or not.
I sent a message via whisperfish (please see [screenshot here](https://i.imgur.com/lqAv0RS.png) )
which was 'seen' three times by the desktop client (pease see [screenshot here](https://i.imgur.com/hV1korY.png) ) of which only the second message has two check marks. 

To me it looks like whisperfish sends the message several times if its not sure whether the message reached the server or no (is that possible?). During the messaging, I was sure to have proper mobile network connection. However, I switched from wifi a few minutes before sending the message (not sure whether whisperfish already re-established the connection at that point in time because the whiserpfish logo on the home screen is more or less always orange for me after some time)

**Comment by aebruno** [comment]
> To me it looks like whisperfish sends the message several times if its not sure whether the message reached the server or no (is that possible?).

No, the most recent version of whisperfish will only attempt to send the message once. If there is no network connection or it fails to contact the server, whisperfish will fail to send the message. There will be no sent check mark next to the message. You can check under "Settings -> Statistics" how many "Unsent" messages there are. In the future I'd like to add the ability display unsent messages and possibly resend them. For now, you can long press on a message that hasn't been sent and resend. 

>  However, I switched from wifi a few minutes before sending the message

Whisperfish will reconnect but I have noticed some odd behavior occasionally when switching from cellular to wifi. But when this happens the websocket connection isn't re-established properly and no messages are received. Which is different from what you describe here. 

Your issue seems to be duplicate messages being sent. Without being able to reproduce this it will be difficult to track down. Sending messages is bound to a Qt signal in the UI so perhaps something odd happened where the UI sent a duplicate signal and whisperfish sent the message twice? 

Let me know if you're able to reproduce.
