### ISSUE TITLE
Whisperfish showing notifications for messages that are already read

### ISSUE THREAD

**Issue by rodneyrod** [aebruno/whisperfish#76]
Every time a user sends a message, it adds that to the notifications, but after opening one message from that user, which allows you to see the other messages too, the notifications will still stay as though they're not read.

**Comment by aebruno** [comment]
This is expected behavior. If you want to clear out the messages from the event screen just long press on the contact name and you can clear all messages for that contact. See #6 for related discussion.

**Comment by bonanza123** [comment]
@aebruno would it be possible to make this configurable? I.e. having an option to choose between clearing the notification on read and the current behavior?

**Comment by d9h02f** [comment]
@aebruno Jolla's Messages application removes all message notifications once one of them is opened, because the idea is that you will read all messages at once. I think this is how most other messaging applications do it, too.

**Comment by aebruno** [comment]
@d9h02f Thanks, I assumed this is how the other apps worked. I'll dig some more and try and fix.

**Comment by sfbg** [comment]
The issue is not consistently solved for me in v 0.5
Old notifications are still visible even after for a conversation in which I have been actively chatting in.
The notifications have to be removed as soon as I enter the chat, regardless where I come from, i.e. from the conversations overview within Whisperfish itself.

**Comment by sfbg** [comment]
It is better now, but i still see a usability issue here.
If I stay within a chat, don't leave it and do not tap on any of the entries in the notification screen, the notifications will still stay forever if I am chatting actively with this one participant, meaning that I for sure have seen those messages. Same if I go in an out of the app from the homescreen.

I think the deletion has to be triggered also when:
 - Answering in a specific chat
 - Open Whisperfish from the multitasking home screen (and go directly into the chat, because this is where I left it open when I minimized the app last time)

**Comment by laubblaeser** [comment]
This is still an issue. Manually removing notifications is a bit of an annoyance I'd like to get rid of. Would it be possible to fix this?

Notifications should be removed from event view whenever the respective conversation is opened in the app.
